#!/bin/sh

# run while loop for boot_completed status & sleep 10 needed for magisk service.d
while [ "$(getprop sys.boot_completed | tr -d '\r')" != "1" ]; do sleep 1; done
sleep 10

# save currently active function name
echo "$(ls -al /config/usb_gadget/g1/configs/b.1/)" | grep -Eo f1.* | awk '{print $3}' | cut -d/ -f8 > /data/adb/.fixdd

# loop
# run every 0.5 seconds
while true
do
  # check the app is active
  chkapp="$(pgrep -f drivedroid | wc -l)"
  # check currently active function
  chkfn=$(echo "$(ls -al /config/usb_gadget/g1/configs/b.1/)" | grep -Eo f1.* | awk '{print $3}' | cut -d/ -f8)
  # load previous active function
  chkfrstfn="$(cat /data/adb/.fixdd)"
  if [ "$chkapp" -eq "1" ] && [ "$chkfn" != "mass_storage.usb0" ]; then
    # add mass_storage.usb0 config & function and remove currently active function
    rm /config/usb_gadget/g1/configs/b.1/f*
    mkdir -p /config/usb_gadget/g1/functions/mass_storage.usb0/lun.0/
    ln -s /config/usb_gadget/g1/functions/mass_storage.usb0 /config/usb_gadget/g1/configs/b.1/f1
  elif [ "$chkapp" -eq "0" ] && [ "$chkfn" = "mass_storage.usb0" ]; then
    # remove mass_storage.usb0 function & restore previous function
    rm /config/usb_gadget/g1/configs/b.1/f*
    ln -s /config/usb_gadget/g1/functions/"$chkfrstfn" /config/usb_gadget/g1/configs/b.1/f1
   if [ "$chkfrstfn" = "ffs.adb" ]; then
    setprop sys.usb.config adb
   elif [ "$chkfrstfn" = "ffs.mtp" ]; then
    setprop sys.usb.config mtp
   fi
  fi
  sleep 0.5
done
